backend:
  name: proxy
  proxy_url: http://localhost:8081/api/v1
media_folder: assets
collections:
  - label: Test
    name: test
    files:
      - file: test.yml
        name: test
        label: Test
        fields:
          - name: test_widget
            label: Test Widget
            widget: test
